spring:
  application:
    name: user-microservice
  profiles:
    active:
    - dev
#  mongodb:
#    uri: mongodb://localhost:27017/userDB
  config:
    import: optional:configserver:http://localhost:8888